// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPLf5SnIA6lt8fx0xiXai9dfsLVGoaI5A',
    appId: '1:806493477706:web:53a45c3ad69164843abfb3',
    messagingSenderId: '806493477706',
    projectId: 'shoe1-f0e53',
    authDomain: 'shoe1-f0e53.firebaseapp.com',
    storageBucket: 'shoe1-f0e53.firebasestorage.app',
    measurementId: 'G-6FH2CHWFGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7xwbLTvS_B4ma_qz0BRpniQZO9aNeW5Q',
    appId: '1:806493477706:android:3578f7d46713e3e13abfb3',
    messagingSenderId: '806493477706',
    projectId: 'shoe1-f0e53',
    storageBucket: 'shoe1-f0e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3H5JS4lt5ehSGJ6UCHasGkUTm2wojOWs',
    appId: '1:806493477706:ios:650714da6b0d0c1d3abfb3',
    messagingSenderId: '806493477706',
    projectId: 'shoe1-f0e53',
    storageBucket: 'shoe1-f0e53.firebasestorage.app',
    iosBundleId: 'com.example.shoe',
  );
}
